/* docgen.js — generate MIND-MAP.md and MIG-SYSTEM.md from the live data.
   These two documents describe 143 nodes and 14 environments. Hand-written,
   they would be wrong within a week. Generated, they cannot drift.

   usage: node tools/docgen.js preview.html
   Re-run after any change to MIGS / MINORS / THOUGHTS / EDGES / WORLDS.
*/
const fs = require('fs');
const file = process.argv[2] || 'preview.html';
const src = fs.readFileSync(file, 'utf8');

function grab(name, open='['){
  const i = src.indexOf('var ' + name + '=' + open);
  if (i < 0) throw new Error('missing ' + name);
  const close = open === '[' ? ']' : '}';
  let j = src.indexOf(open, i), d = 0, k = j;
  for (; k < src.length; k++){ if (src[k] === open) d++; else if (src[k] === close){ d--; if (!d) break; } }
  return eval('(' + src.slice(j, k + 1) + ')');
}
const MIGS = grab('MIGS'), MINORS = grab('MINORS'), THOUGHTS = grab('THOUGHTS'),
      EDGES = grab('EDGES'), WORLDS = grab('WORLDS', '{');

const nodes = [...MIGS.map(m => ({...m, t:'mig', mig:m.id})), ...MINORS.map(m => ({...m, t:'minor'})), ...THOUGHTS];
const byId = {}; nodes.forEach(n => byId[n.id] = n);
const owned = {}; MIGS.forEach(m => owned[m.id] = []);
nodes.forEach(n => { if (n.t !== 'mig') owned[n.mig].push(n); });
const deg = {}; nodes.forEach(n => deg[n.id] = 0);
EDGES.forEach(e => { deg[e[0]]++; deg[e[1]]++; });

const stamp = new Date().toISOString().slice(0, 10);
const esc = s => String(s).replace(/\|/g, '\\|');

/* ── MIND-MAP.md ───────────────────────────────────────────────── */
let mm = `# MIND-MAP.md — the conceptual architecture

**Generated by \`tools/docgen.js\` from \`${file}\` on ${stamp}. Do not edit by hand.**
Re-run after any data change: \`node tools/docgen.js preview.html\`

${nodes.length} nodes · ${EDGES.length} relationships · ${MIGS.length} regions ·
${MINORS.length} concepts · ${THOUGHTS.length} writings

---

## The regions

| Region | Concepts | Writings | Reach out | Reach in |
|---|--:|--:|--:|--:|
`;
MIGS.forEach(m => {
  const mine = owned[m.id];
  const out = new Set(), inn = new Set();
  mine.forEach(n => (n.crosses||[]).forEach(c => out.add(c)));
  nodes.forEach(n => { if (n.t !== 'mig' && n.mig !== m.id && (n.crosses||[]).includes(m.id)) inn.add(n.mig); });
  mm += `| **${m.label}** | ${mine.filter(n=>n.t==='minor').length} | ${mine.filter(n=>n.t!=='minor').length} | ${out.size} | ${inn.size} |\n`;
});

mm += `\n---\n\n## Where the traffic is\n\nThe most connected ideas — these are the junctions a wandering visitor keeps\nhitting, and they carry the site's cross-disciplinary weight.\n\n| Node | Region | Kind | Edges |\n|---|---|---|--:|\n`;
nodes.filter(n => n.t !== 'mig').sort((a,b) => deg[b.id]-deg[a.id]).slice(0, 15).forEach(n => {
  mm += `| ${esc(n.label)} | ${byId[n.mig].label.toLowerCase()} | ${n.t} | ${deg[n.id]} |\n`;
});

const deadEnds = nodes.filter(n => n.t !== 'mig' && n.t !== 'minor' && deg[n.id] === 1);
mm += `\n## Dead ends\n\n${deadEnds.length} of ${THOUGHTS.length} writings have exactly one relationship. A visitor who\narrives at one can only go back the way they came, which is the opposite of a\ncuriosity loop. These are the highest-value targets for new relationships.\n\n`;
deadEnds.forEach(n => { mm += `- \`${n.id}\` — ${esc(n.label)} *(${byId[n.mig].label.toLowerCase()})*\n`; });

mm += `\n---\n\n## Every region in full\n`;
MIGS.forEach(m => {
  mm += `\n### ${m.label}\n\n> ${m.line}\n\n`;
  const minors = owned[m.id].filter(n => n.t === 'minor');
  const writ = owned[m.id].filter(n => n.t !== 'minor');
  if (!minors.length && !writ.length){ mm += `*Empty by design. No source material exists; inventing some would make the rest of the site less trustworthy.*\n`; return; }
  if (minors.length){
    mm += `**Concepts** — ${minors.map(n => esc(n.label) + (n.g ? ' ●' : '')).join(' · ')}\n\n`;
  }
  if (writ.length){
    mm += `| Writing | Kind | State | Register | Source | Edges |\n|---|---|---|---|---|--:|\n`;
    writ.forEach(n => {
      mm += `| ${esc(n.label)} | ${n.t} | ${n.state} | ${esc(n.register||'—')} | ${esc(n.src||'**none**')} | ${deg[n.id]} |\n`;
    });
    mm += `\n`;
  }
});

mm += `\n---\n\n## Cross-region relationships\n\n${EDGES.filter(e => byId[e[0]].mig !== byId[e[1]].mig).length} of ${EDGES.length} relationships cross a region boundary. These are the routes\nthat let a visitor lose track of which section they are in.\n\n| From | verb | To | Crossing |\n|---|---|---|---|\n`;
EDGES.filter(e => byId[e[0]].mig !== byId[e[1]].mig).forEach(e => {
  mm += `| ${esc(byId[e[0]].label)} | *${esc(e[2])}* | ${esc(byId[e[1]].label)} | ${byId[e[0]].mig} → ${byId[e[1]].mig} |\n`;
});

fs.writeFileSync('MIND-MAP.md', mm, 'utf8');

/* ── MIG-SYSTEM.md ─────────────────────────────────────────────── */
const lum = c => (0.2126*c[0] + 0.7152*c[1] + 0.0722*c[2]) / 255;
const isTeal = c => c[1] > 90 && c[2] >= c[1] && c[2]-c[1] <= 12 && c[2]-c[0] > 40;

let ms = `# MIG-SYSTEM.md — the environment specification

**Generated by \`tools/docgen.js\` from \`${file}\` on ${stamp}. Do not edit by hand.**

Each region declares its own light, physics and composition. The neuron and the
document do not change — see [DESIGN.md](DESIGN.md) §1.

---

## The environment profile

| Region | env | ring | rim | anchor | ease | sway | dens | ground | light |
|---|---|---|---|---|--:|---|--:|---|---|
`;
MIGS.forEach(m => {
  const w = WORLDS[m.id];
  ms += `| **${m.label}** | ${w.env} | ${w.ring} | ${w.rim||'ellipse'} | ${(w.anchor||[.5,.5]).join(', ')} | ${w.ease} | ${JSON.stringify(w.sway||0)} | ${w.dens} | rgb(${w.ground.join(',')}) | ${lum(w.ground) > .5 ? '**light**' : 'dark'} |\n`;
});

ms += `\n**Light-ground regions:** ${MIGS.filter(m => lum(WORLDS[m.id].ground) > .5).map(m => m.label).join(', ')}\n`;
ms += `\n**Teal used as material:** ${MIGS.filter(m => isTeal(WORLDS[m.id].tone)).map(m => m.label).join(', ') || 'none'} — nowhere else.\n`;
const eases = MIGS.map(m => WORLDS[m.id].ease);
ms += `\n**Motion spread:** ${Math.min(...eases)} (slowest) → ${Math.max(...eases)} (fastest), a ${(Math.max(...eases)/Math.min(...eases)).toFixed(0)}× range.\n`;

ms += `\n---\n\n## Differentiation audit\n\nHow much page composition each region actually overrides, measured from the CSS.\nA region carried only by colour tokens will not read as "somewhere else" — the\nbrief (§35) requires recognition without reading the title.\n\n| Region | CSS rules | CSS chars | Verdict |\n|---|--:|--:|---|\n`;
const css = (src.match(/<style>[\s\S]*?<\/style>/)||[''])[0];
MIGS.map(m => {
  const rules = css.match(new RegExp('html\\.w-' + m.id + '(?![\\w-])[^{]*\\{[^}]*\\}', 'g')) || [];
  return { m, n: rules.length, c: rules.join('').length };
}).sort((a,b) => a.c - b.c).forEach(({m,n,c}) => {
  const verdict = c < 300 ? '**thin — colour only**' : c < 600 ? 'moderate' : 'strongly composed';
  ms += `| ${m.label} | ${n} | ${c} | ${verdict} |\n`;
});

ms += `\n---\n\n## Per-region briefs\n\nThe canvas painter (\`env\`) and arrangement (\`ring\`) carry the atmosphere; the\nCSS carries the page. Both are listed so a change to one can be checked against\nthe other.\n`;
MIGS.forEach(m => {
  const w = WORLDS[m.id];
  const writ = owned[m.id].filter(n => n.t !== 'minor').length;
  ms += `\n### ${m.label}\n\n> ${m.line}\n\n`;
  ms += `- **painter** \`${w.env}\` · **arrangement** \`${w.ring}\` · **rim** \`${w.rim||'ellipse'}\`\n`;
  ms += `- **anchor** \`[${(w.anchor||[.5,.5]).join(', ')}]\`${(w.anchor||[.5,.5]).join(',') === '0.5,0.5' ? ' — the one region allowed dead centre' : ''}\n`;
  ms += `- **motion** ease \`${w.ease}\`, sway \`${JSON.stringify(w.sway||0)}\`\n`;
  ms += `- **ground** \`rgb(${w.ground.join(',')})\` ${lum(w.ground) > .5 ? '(light)' : '(dark)'} · **accent** \`rgb(${w.accent.join(',')})\` · **tone** \`rgb(${w.tone.join(',')})\`${isTeal(w.tone) ? ' — teal, as material' : ''}\n`;
  ms += `- **content** ${owned[m.id].filter(n=>n.t==='minor').length} concepts, ${writ} writings${writ === 0 ? ' — **empty by design**' : writ <= 2 ? ' — **thin, needs material**' : ''}\n`;
});

fs.writeFileSync('MIG-SYSTEM.md', ms, 'utf8');
console.log('wrote MIND-MAP.md (' + mm.length + ' chars) and MIG-SYSTEM.md (' + ms.length + ' chars)');
