/* p6queue.js — build the P6 review queue.

   The 19 single-edge writings are dead ends: a visitor who reaches one can only
   go back the way they came. Each needs more relationships.

   This script finds PLAUSIBLE TOPOLOGY ONLY. It never writes a gloss and never
   creates an edge. A relationship's gloss is a first-person claim about why two
   of Siddhesh's ideas connect — the file inventing forty of those is exactly
   the failure this project has already been burned by once.

   Candidate signals, strongest first:
     A  the ingestion record already logged the connection, and no edge exists
     B  the writing declares crosses:[MIG] but has no edge reaching that MIG
     C  distinctive vocabulary shared with another object's own words
     D  same region, same concept cluster, not yet connected

   usage: node tools/p6queue.js preview.html
*/
const fs = require('fs');
const file = process.argv[2] || 'preview.html';
const src = fs.readFileSync(file, 'utf8');
const inv = JSON.parse(fs.readFileSync('content-inventory.json', 'utf8')).objects;

function grab(name, open='['){
  const i = src.indexOf('var ' + name + '=' + open);
  const close = open === '[' ? ']' : '}';
  let j = src.indexOf(open, i), d = 0, k = j;
  for (; k < src.length; k++){ if (src[k] === open) d++; else if (src[k] === close){ d--; if (!d) break; } }
  return eval('(' + src.slice(j, k + 1) + ')');
}
const MIGS = grab('MIGS'), MINORS = grab('MINORS'), THOUGHTS = grab('THOUGHTS'), EDGES = grab('EDGES');
const nodes = [...MIGS.map(m => ({...m, t:'mig', mig:m.id})), ...MINORS.map(m => ({...m, t:'minor'})), ...THOUGHTS];
const byId = {}; nodes.forEach(n => byId[n.id] = n);
const adj = {}; nodes.forEach(n => adj[n.id] = []);
EDGES.forEach(e => { adj[e[0]].push({o:e[1], e, dir:'out'}); adj[e[1]].push({o:e[0], e, dir:'in'}); });
const linked = (a,b) => adj[a].some(k => k.o === b);

const STOP = new Set(('about above after again against because been before being between both cannot could during '+
 'each from further having here into itself more most other over same should some such than that their theirs them '+
 'then there these they this those through under until very were what when where which while with would your '+
 'people things something someone always never every').split(' '));
const words = s => [...new Set(String(s||'').toLowerCase().match(/[a-z']{5,}/g) || [])].filter(w => !STOP.has(w));

/* map inventory ids -> live ids by matching quote/title against label/line */
const flat = s => String(s||'').toLowerCase().replace(/[^a-z0-9 ]+/g,'').replace(/\s+/g,' ').trim();
const invToLive = {};
inv.forEach(o => {
  const q = flat(o.quote), t = flat(o.title);
  const hit = nodes.find(n => {
    const L = flat(n.line), B = flat(n.label);
    return (q.length > 18 && (L.includes(q) || q.includes(L))) || (t.length > 6 && B === t);
  });
  if (hit) invToLive[o.id] = hit.id;
});

const deadEnds = THOUGHTS.filter(t => adj[t.id].length === 1);

let md = `# P6-REVIEW-QUEUE.md — dead ends awaiting your reasoning

**Generated by \`tools/p6queue.js\`. Regenerate after any edge is added.**

${deadEnds.length} of ${THOUGHTS.length} writings have exactly one relationship. A visitor who reaches one
can only go back the way they came, which is the opposite of a curiosity loop.

**What this file is.** Plausible topology, found from the ingestion record, your
declared region crossings, and shared vocabulary. **No gloss has been written and
no edge has been created.** Every candidate below stops at the point where a
first-person claim is needed — that claim is yours.

**How to use it.** For any candidate you accept, give me the verb and one
sentence of reasoning. I will add the edge, in the direction you state, and
re-run the validators.

Direction matters: the site always renders a relationship in the edge's own
direction, so \`A → verb → B\` and \`B → verb → A\` say different things.

---

`;

deadEnds.forEach((w, i) => {
  const only = adj[w.id][0];
  const other = byId[only.o];
  const home = byId[w.mig];
  // its concept cluster: the minor IG it hangs off, if any
  const minorLink = adj[w.id].map(k => byId[k.o]).find(n => n.t === 'minor');
  const invRec = inv.find(o => invToLive[o.id] === w.id);

  const cand = {};
  const add = (id, score, why) => {
    if (!id || id === w.id || !byId[id] || linked(w.id, id)) return;
    if (byId[id].t === 'mig') return;
    cand[id] = cand[id] || { score:0, why:[] };
    cand[id].score += score; cand[id].why.push(why);
  };

  // A — the ingestion record already logged it
  if (invRec && invRec.connections) invRec.connections.forEach(c => {
    const live = invToLive[c] || (byId[c] ? c : null);
    if (live) add(live, 6, 'the ingestion record logged this connection against `' + invRec.id + '` and no edge was ever made');
  });

  // B — a declared crossing with nothing realising it
  (w.crosses || []).forEach(mid => {
    const reaches = adj[w.id].some(k => byId[k.o].mig === mid);
    if (reaches) return;
    MINORS.filter(mn => mn.mig === mid).slice(0, 3).forEach(mn =>
      add(mn.id, 4, 'this writing declares it crosses into **' + byId[mid].label.toLowerCase() +
                    '** but no edge reaches that region'));
  });

  // C — distinctive vocabulary shared with another object's own words
  const mine = words(w.line + ' ' + w.label);
  nodes.filter(n => n.t !== 'mig' && n.id !== w.id).forEach(n => {
    const shared = words(n.line + ' ' + n.label).filter(x => mine.includes(x));
    if (shared.length >= 2) add(n.id, 2 + shared.length, 'shares the words *' + shared.slice(0,3).join(', ') + '* with its own text');
  });

  // D — same region, same cluster
  if (minorLink) MINORS.filter(mn => mn.mig === w.mig && mn.id !== minorLink.id)
    .slice(0, 2).forEach(mn => add(mn.id, 1, 'sits in the same region, one concept across'));

  const ranked = Object.entries(cand).sort((a,b) => b[1].score - a[1].score).slice(0, 4);

  md += `## ${i+1}. \`${w.id}\` — ${w.label}\n\n`;
  md += `> ${w.line}\n\n`;
  md += `| | |\n|---|---|\n`;
  md += `| Region | ${home.label.toLowerCase()} |\n`;
  md += `| Concept | ${minorLink ? minorLink.label.toLowerCase() : '**none — it hangs off no concept**'} |\n`;
  md += `| Kind | ${w.t} · ${w.state} · ${w.register || '—'} |\n`;
  md += `| Source | ${w.src || '**none**'} |\n`;
  md += `| Its one relationship | ${only.dir === 'out'
      ? '`' + w.label + '` — *' + only.e[2] + '* → `' + other.label + '`'
      : '`' + other.label + '` — *' + only.e[2] + '* → `' + w.label + '`'} |\n\n`;

  if (!ranked.length){ md += `*No candidate reached the threshold from existing material. This one needs you to name where it belongs.*\n\n---\n\n`; return; }

  md += `**Candidates**\n\n`;
  ranked.forEach(([id, c]) => {
    const n = byId[id];
    md += `- **\`${id}\`** — ${n.label.toLowerCase()} *(${n.t}, ${byId[n.mig].label.toLowerCase()})*\n`;
    md += `  - ${[...new Set(c.why)].join('; ')}\n`;
    if (n.line) md += `  - its text: “${n.line.length > 150 ? n.line.slice(0,150) + '…' : n.line}”\n`;
    md += `  - supporting source: ${n.src ? '`' + n.src + '`' : '*scaffolding, no source*'}` +
          (w.src ? ` and \`${w.src}\`` : '') + `\n`;
  });
  md += `\n**Your call:** for each candidate you want, give me the **verb** and **one sentence** saying why the two connect. ` +
        `Say nothing for the ones you reject.\n\n---\n\n`;
});

md += `## What I need back

For anything you accept, this shape is enough:

\`\`\`
b-dreams -> motivation
verb: outlasts
"Motivation is weather. This is the thing I do when it is not there."
\`\`\`

I will add the edge in that direction, keep your sentence verbatim as the gloss,
and re-run \`validate.js\` and \`accept.js\`.
`;

fs.writeFileSync('P6-REVIEW-QUEUE.md', md, 'utf8');
console.log('wrote P6-REVIEW-QUEUE.md — ' + deadEnds.length + ' dead ends, ' +
            deadEnds.filter(w => adj[w.id].length === 1).length + ' queued');
